services:
  shrls:
    # Uncomment to build from source
    #build:
    #  context: .
    image: ghcr.io/demophoon/shrls:latest
    environment:
      SHRLS_DEFAULT_REDIRECT: "https://www.brittg.com/"
      SHRLS_UPLOAD_DIRECTORY: "/uploads"
      SHRLS_USERNAME: "admin"
      SHRLS_PASSWORD: "changeMe!"
      # Uncomment to use mongodb backend
      # SHRLS_MONGO_CONNECTION_STRING: "mongodb://mongo:password@mongodb:27017"
    ports:
      - "5000:3000"
    volumes:
      - "${PWD}/config:/config"
      - "${PWD}/uploads:/uploads"

  # Uncomment to use mongodb
  #mongodb:
  #  image: mongo
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: mongo
  #    MONGO_INITDB_ROOT_PASSWORD: password
