name: Docker Image CI

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Build the Docker image
      run: make docker version={{ github.ref_name }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push Docker image
      run: |
        make publish version={{ github.ref_name }}
